version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.4
    steps:
      - checkout
      - run:
          command: cd app && npm install --production
      - persist_to_workspace:
          root: ~/
          paths: project
  package:
    docker:
      - image: circleci/node:10.4
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Package
          command: cd app && zip ../dist/lambda.zip -r ./*
      - persist_to_workspace:
          root: ~/
          paths: project
  deploy:
    docker:
      - image: cibuilds/aws:1.16.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy to AWS
          command: |
            echo 'export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV
            echo 'export AWS_REGION=${AWS_REGION}' >> $BASH_ENV
            source $BASH_ENV
            aws lambda update-function-code --zip-file fileb://dist/lambda.zip --function-name ${FUNCTION_NAME} > /dev/null

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - package:
          filters:
            branches:
              only: master
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - package
